export const Translations = [
    { Id: 1, en_us: "Morgan Market Insights", zh_cn: "摩根市場洞察" },
    { Id: 2, en_us: "Search by Name", zh_cn: "按名稱搜尋" },
    { Id: 3, en_us: "Enter name...", zh_cn: "輸入名稱..." },
    { Id: 4, en_us: "Industry", zh_cn: "行業" },
    { Id: 5, en_us: "All Industries", zh_cn: "所有行業" },
    { Id: 6, en_us: "Market Cap", zh_cn: "市值" },
    { Id: 7, en_us: "Total Equity", zh_cn: "總權益" },
    { Id: 8, en_us: "Total Debt", zh_cn: "總債務" },
    { Id: 9, en_us: "Debt-to-Equity Ratio", zh_cn: "債務權益比" },
    { Id: 10, en_us: "Investment Strategy", zh_cn: "投資策略" },
    { Id: 11, en_us: "All Strategies", zh_cn: "所有策略" },
    { Id: 12, en_us: "Export to CSV", zh_cn: "匯出為CSV" },
    { Id: 13, en_us: "Delete Selected", zh_cn: "刪除選定" },
    { Id: 14, en_us: "Edit", zh_cn: "編輯" },
    { Id: 15, en_us: "Edit Company", zh_cn: "編輯公司" },
    { Id: 16, en_us: "Save", zh_cn: "儲存" },
    { Id: 17, en_us: "Cancel", zh_cn: "取消" },
    { Id: 18, en_us: "Name", zh_cn: "名稱" },
    { Id: 19, en_us: "Headquarters", zh_cn: "總部" },
    { Id: 20, en_us: "Email", zh_cn: "電子郵件" },
    { Id: 21, en_us: "Phone", zh_cn: "電話" },
    { Id: 22, en_us: "Address", zh_cn: "地址" },
    { Id: 23, en_us: "Country", zh_cn: "國家" },
    { Id: 24, en_us: "Convertible Bonds", zh_cn: "可轉換債券" },
    { Id: 25, en_us: "Preferred Stock", zh_cn: "優先股" },
    { Id: 26, en_us: "Bonds", zh_cn: "債券" },
    { Id: 27, en_us: "Green Bonds", zh_cn: "綠色債券" },
    { Id: 28, en_us: "Last Updated", zh_cn: "最後更新" },
    { Id: 29, en_us: "Total Investments", zh_cn: "總投資" },
    { Id: 30, en_us: "Portfolio Exits", zh_cn: "投資組合退出" },
    { Id: 31, en_us: "Average Return", zh_cn: "平均回報" },
    { Id: 32, en_us: "Years Active", zh_cn: "活躍年數" },
    { Id: 33, en_us: "Switch to Chinese", zh_cn: "切換到英文" },
    { Id: 34, en_us: "Actions", zh_cn: "操作" },
    { Id: 35, en_us: "General Information", zh_cn: "基本信息" },
    { Id: 36, en_us: "Capital Structure", zh_cn: "資本結構" },
    { Id: 37, en_us: "Investment Experience", zh_cn: "投資經驗" },
    { Id: 38, en_us: "Close", zh_cn: "關閉" },
    { Id: 39, en_us: "Timeframe", zh_cn: "時間範圍" },
    { Id: 40, en_us: "Custom Timeframe", zh_cn: "自訂時間範圍" },
    { Id: 41, en_us: "Start Date", zh_cn: "開始日期" },
    { Id: 42, en_us: "End Date", zh_cn: "結束日期" },
    { Id: 43, en_us: "Apply", zh_cn: "應用" },
    { Id: 44, en_us: "Please select both start and end dates.", zh_cn: "請選擇開始和結束日期。" },
    // Translations for companyDetailsData
    { Id: 45, en_us: "Acme Corporation", zh_cn: "頂峰公司" },
    { Id: 46, en_us: "Technology", zh_cn: "科技" },
    { Id: 47, en_us: "San Francisco, CA, USA", zh_cn: "美國加利福尼亞州舊金山" },
    { Id: 48, en_us: "Blue Horizon Ltd.", zh_cn: "藍色地平線有限公司" },
    { Id: 49, en_us: "Finance", zh_cn: "金融" },
    { Id: 50, en_us: "New York, NY, USA", zh_cn: "美國紐約州紐約市" },
    { Id: 51, en_us: "Green Energy Solutions", zh_cn: "綠色能源解決方案" },
    { Id: 52, en_us: "Renewable Energy", zh_cn: "可再生能源" },
    { Id: 53, en_us: "Austin, TX, USA", zh_cn: "美國德克薩斯州奧斯汀" },
    { Id: 54, en_us: "Quantum Dynamics", zh_cn: "量子動力" },
    { Id: 55, en_us: "Quantum Computing", zh_cn: "量子計算" },
    { Id: 56, en_us: "Boston, MA, USA", zh_cn: "美國馬薩諸塞州波士頓" },
    { Id: 57, en_us: "Health Innovations Group", zh_cn: "健康創新集團" },
    { Id: 58, en_us: "Healthcare", zh_cn: "醫療保健" },
    { Id: 59, en_us: "Chicago, IL, USA", zh_cn: "美國伊利諾伊州芝加哥" },
    { Id: 60, en_us: "Skyline Aerospace", zh_cn: "天際航空" },
    { Id: 61, en_us: "Aerospace", zh_cn: "航空航天" },
    { Id: 62, en_us: "Seattle, WA, USA", zh_cn: "美國華盛頓州西雅圖" },
    { Id: 63, en_us: "Global Logistics Inc.", zh_cn: "全球物流公司" },
    { Id: 64, en_us: "Logistics", zh_cn: "物流" },
    { Id: 65, en_us: "Miami, FL, USA", zh_cn: "美國佛羅里達州邁阿密" },
    { Id: 66, en_us: "CyberShield Technologies", zh_cn: "網絡盾牌科技" },
    { Id: 67, en_us: "Cybersecurity", zh_cn: "網絡安全" },
    { Id: 68, en_us: "Palo Alto, CA, USA", zh_cn: "美國加利福尼亞州帕洛阿爾托" },
    { Id: 69, en_us: "Urban Mobility Solutions", zh_cn: "城市移動解決方案" },
    { Id: 70, en_us: "Transportation", zh_cn: "運輸" },
    { Id: 71, en_us: "Los Angeles, CA, USA", zh_cn: "美國加利福尼亞州洛杉磯" },
    { Id: 72, en_us: "AgriTech Ventures", zh_cn: "農業科技創投" },
    { Id: 73, en_us: "Agriculture", zh_cn: "農業" },
    { Id: 74, en_us: "Des Moines, IA, USA", zh_cn: "美國艾奧瓦州得梅因" },
    { Id: 75, en_us: "Smart Retail Corp.", zh_cn: "智能零售公司" },
    { Id: 76, en_us: "Retail", zh_cn: "零售" },
    { Id: 77, en_us: "Dallas, TX, USA", zh_cn: "美國德克薩斯州達拉斯" },
    { Id: 78, en_us: "BioEnergy Partners", zh_cn: "生物能源合作夥伴" },
    { Id: 79, en_us: "Bioenergy", zh_cn: "生物能源" },
    { Id: 80, en_us: "Denver, CO, USA", zh_cn: "美國科羅拉多州丹佛" },
    { Id: 81, en_us: "EdTech Innovators", zh_cn: "教育科技創新者" },
    { Id: 82, en_us: "Education Technology", zh_cn: "教育科技" },
    { Id: 83, en_us: "San Diego, CA, USA", zh_cn: "美國加利福尼亞州聖地亞哥" },
    { Id: 84, en_us: "English", zh_cn: "英文" },
    { Id: 85, en_us: "Chinese", zh_cn: "中文" },
    { Id: 86, en_us: "Navigation", zh_cn: "導航" },
    { Id: 87, en_us: "Companies", zh_cn: "公司" },
    { Id: 88, en_us: "Visualizations", zh_cn: "可視化" }
];