export const Translations = [
    { Id: 1, en_us: "Morgan Market Insights", zh_tw: "摩根市場洞察" },
    { Id: 2, en_us: "Search by Name", zh_tw: "按名稱搜尋" },
    { Id: 3, en_us: "Enter name...", zh_tw: "輸入名稱..." },
    { Id: 4, en_us: "Industry", zh_tw: "行業" },
    { Id: 5, en_us: "All Industries", zh_tw: "所有行業" },
    { Id: 6, en_us: "Market Cap", zh_tw: "市值" },
    { Id: 7, en_us: "Total Equity", zh_tw: "總權益" },
    { Id: 8, en_us: "Total Debt", zh_tw: "總債務" },
    { Id: 9, en_us: "Debt-to-Equity Ratio", zh_tw: "債務權益比" },
    { Id: 10, en_us: "Investment Strategy", zh_tw: "投資策略" },
    { Id: 11, en_us: "All Strategies", zh_tw: "所有策略" },
    { Id: 12, en_us: "Export to CSV", zh_tw: "匯出為CSV" },
    { Id: 13, en_us: "Delete Selected", zh_tw: "刪除選定" },
    { Id: 14, en_us: "Edit", zh_tw: "編輯" },
    { Id: 15, en_us: "Edit Company", zh_tw: "編輯公司" },
    { Id: 16, en_us: "Save", zh_tw: "儲存" },
    { Id: 17, en_us: "Cancel", zh_tw: "取消" },
    { Id: 18, en_us: "Name", zh_tw: "名稱" },
    { Id: 19, en_us: "Headquarters", zh_tw: "總部" },
    { Id: 20, en_us: "Email", zh_tw: "電子郵件" },
    { Id: 21, en_us: "Phone", zh_tw: "電話" },
    { Id: 22, en_us: "Address", zh_tw: "地址" },
    { Id: 23, en_us: "Country", zh_tw: "國家" },
    { Id: 24, en_us: "Convertible Bonds", zh_tw: "可轉換債券" },
    { Id: 25, en_us: "Preferred Stock", zh_tw: "優先股" },
    { Id: 26, en_us: "Bonds", zh_tw: "債券" },
    { Id: 27, en_us: "Green Bonds", zh_tw: "綠色債券" },
    { Id: 28, en_us: "Last Updated", zh_tw: "最後更新" },
    { Id: 29, en_us: "Total Investments", zh_tw: "總投資" },
    { Id: 30, en_us: "Portfolio Exits", zh_tw: "投資組合退出" },
    { Id: 31, en_us: "Average Return", zh_tw: "平均回報" },
    { Id: 32, en_us: "Years Active", zh_tw: "活躍年數" },
    { Id: 33, en_us: "Switch to Chinese", zh_tw: "切換到英文" },
    { Id: 34, en_us: "Actions", zh_tw: "操作" },
    { Id: 35, en_us: "General Information", zh_tw: "基本信息" },
    { Id: 36, en_us: "Capital Structure", zh_tw: "資本結構" },
    { Id: 37, en_us: "Investment Experience", zh_tw: "投資經驗" },
    { Id: 38, en_us: "Close", zh_tw: "關閉" },
    { Id: 39, en_us: "Timeframe", zh_tw: "時間範圍" },
    { Id: 40, en_us: "Custom Timeframe", zh_tw: "自訂時間範圍" },
    { Id: 41, en_us: "Start Date", zh_tw: "開始日期" },
    { Id: 42, en_us: "End Date", zh_tw: "結束日期" },
    { Id: 43, en_us: "Apply", zh_tw: "應用" },
    { Id: 44, en_us: "Please select both start and end dates.", zh_tw: "請選擇開始和結束日期。" },
    // Translations for companyDetailsData
    { Id: 45, en_us: "Acme Corporation", zh_tw: "頂峰公司" },
    { Id: 46, en_us: "Technology", zh_tw: "科技" },
    { Id: 47, en_us: "San Francisco, CA, USA", zh_tw: "美國加利福尼亞州舊金山" },
    { Id: 48, en_us: "Blue Horizon Ltd.", zh_tw: "藍色地平線有限公司" },
    { Id: 49, en_us: "Finance", zh_tw: "金融" },
    { Id: 50, en_us: "New York, NY, USA", zh_tw: "美國紐約州紐約市" },
    { Id: 51, en_us: "Green Energy Solutions", zh_tw: "綠色能源解決方案" },
    { Id: 52, en_us: "Renewable Energy", zh_tw: "可再生能源" },
    { Id: 53, en_us: "Austin, TX, USA", zh_tw: "美國德克薩斯州奧斯汀" },
    { Id: 54, en_us: "Quantum Dynamics", zh_tw: "量子動力" },
    { Id: 55, en_us: "Quantum Computing", zh_tw: "量子計算" },
    { Id: 56, en_us: "Boston, MA, USA", zh_tw: "美國馬薩諸塞州波士頓" },
    { Id: 57, en_us: "Health Innovations Group", zh_tw: "健康創新集團" },
    { Id: 58, en_us: "Healthcare", zh_tw: "醫療保健" },
    { Id: 59, en_us: "Chicago, IL, USA", zh_tw: "美國伊利諾伊州芝加哥" },
    { Id: 60, en_us: "Skyline Aerospace", zh_tw: "天際航空" },
    { Id: 61, en_us: "Aerospace", zh_tw: "航空航天" },
    { Id: 62, en_us: "Seattle, WA, USA", zh_tw: "美國華盛頓州西雅圖" },
    { Id: 63, en_us: "Global Logistics Inc.", zh_tw: "全球物流公司" },
    { Id: 64, en_us: "Logistics", zh_tw: "物流" },
    { Id: 65, en_us: "Miami, FL, USA", zh_tw: "美國佛羅里達州邁阿密" },
    { Id: 66, en_us: "CyberShield Technologies", zh_tw: "網絡盾牌科技" },
    { Id: 67, en_us: "Cybersecurity", zh_tw: "網絡安全" },
    { Id: 68, en_us: "Palo Alto, CA, USA", zh_tw: "美國加利福尼亞州帕洛阿爾托" },
    { Id: 69, en_us: "Urban Mobility Solutions", zh_tw: "城市移動解決方案" },
    { Id: 70, en_us: "Transportation", zh_tw: "運輸" },
    { Id: 71, en_us: "Los Angeles, CA, USA", zh_tw: "美國加利福尼亞州洛杉磯" },
    { Id: 72, en_us: "AgriTech Ventures", zh_tw: "農業科技創投" },
    { Id: 73, en_us: "Agriculture", zh_tw: "農業" },
    { Id: 74, en_us: "Des Moines, IA, USA", zh_tw: "美國艾奧瓦州得梅因" },
    { Id: 75, en_us: "Smart Retail Corp.", zh_tw: "智能零售公司" },
    { Id: 76, en_us: "Retail", zh_tw: "零售" },
    { Id: 77, en_us: "Dallas, TX, USA", zh_tw: "美國德克薩斯州達拉斯" },
    { Id: 78, en_us: "BioEnergy Partners", zh_tw: "生物能源合作夥伴" },
    { Id: 79, en_us: "Bioenergy", zh_tw: "生物能源" },
    { Id: 80, en_us: "Denver, CO, USA", zh_tw: "美國科羅拉多州丹佛" },
    { Id: 81, en_us: "EdTech Innovators", zh_tw: "教育科技創新者" },
    { Id: 82, en_us: "Education Technology", zh_tw: "教育科技" },
    { Id: 83, en_us: "San Diego, CA, USA", zh_tw: "美國加利福尼亞州聖地亞哥" },
    { Id: 84, en_us: "English", zh_tw: "英文" },
    { Id: 85, en_us: "Chinese", zh_tw: "中文" },
    { Id: 86, en_us: "Navigation", zh_tw: "導航" },
    { Id: 87, en_us: "Companies", zh_tw: "公司" },
    { Id: 88, en_us: "Visualizations", zh_tw: "可視化" },
    { Id: 89, en_us: "Back to Companies", zh_tw: "返回公司" },
    { Id: 90, en_us: "Total Carrying Amount", zh_tw: "總帳面金額" },
    { Id: 91, en_us: "Total Fair Value", zh_tw: "總公允價值" },
    { Id: 92, en_us: "Ownership by Type", zh_tw: "按類型分類的所有權" },
    { Id: 93, en_us: "Account Shares", zh_tw: "帳戶股份" },
    { Id: 94, en_us: "Select Column", zh_tw: "選擇欄位" },
    { Id: 95, en_us: "Carrying Amount", zh_tw: "帳面金額" },
    { Id: 96, en_us: "Fair Value", zh_tw: "公允價值" },
    { Id: 97, en_us: "Reset Filters", zh_tw: "重設篩選" },
    { Id: 98, en_us: "From Year", zh_tw: "起始年份" },
    { Id: 99, en_us: "To Year", zh_tw: "結束年份" },
    { Id: 100, en_us: "Quarter", zh_tw: "季度" },
    { Id: 101, en_us: "Q1", zh_tw: "第一季度" },
    { Id: 102, en_us: "Q2", zh_tw: "第二季度" },
    { Id: 103, en_us: "Q3", zh_tw: "第三季度" },
    { Id: 104, en_us: "Q4", zh_tw: "第四季度" },
    { Id: 104, en_us: "Q4", zh_tw: "第四季度" },
    { Id: 105, en_us: "Company Details", zh_tw: "公司詳情" },
    { Id: 106, en_us: "Collapse Information Section", zh_tw: "摺疊資訊部分" },
    { Id: 107, en_us: "Expand Information Section", zh_tw: "展開資訊部分" },
    { Id: 108, en_us: "Industry", zh_tw: "產業" },
    { Id: 109, en_us: "Market Cap", zh_tw: "市值" },
    { Id: 110, en_us: "Headquarters", zh_tw: "總部" },
    { Id: 111, en_us: "Email", zh_tw: "電子郵件" },
    { Id: 112, en_us: "Phone", zh_tw: "電話" },
    { Id: 113, en_us: "Address", zh_tw: "地址" },
    { Id: 114, en_us: "Company Information", zh_tw: "公司信息" },
    { Id: 115, en_us: "Favorite", zh_tw: "最愛" },
    { Id: 116, en_us: "Type", zh_tw: "類型" },
    { Id: 117, en_us: "Relationship", zh_tw: "關係" },
    { Id: 118, en_us: "Ownership", zh_tw: "所有權" },
    { Id: 119, en_us: "Classification", zh_tw: "分類" },
    { Id: 120, en_us: "Min", zh_tw: "最小值" },
    { Id: 121, en_us: "Max", zh_tw: "最大值" },
    { Id: 122, en_us: "Custom Range", zh_tw: "自訂範圍" },
    { Id: 123, en_us: "Stock", zh_tw: "股票" },
    { Id: 124, en_us: "All Types", zh_tw: "所有類型" },
    { Id: 125, en_us: "Fund", zh_tw: "基金" },
    { Id: 126, en_us: "All Relationships", zh_tw: "所有關係" },
    { Id: 127, en_us: "All Classifications", zh_tw: "所有分類" }
];